#!/usr/bin/python

import math, sys, time, pickle, os.path
from time import gmtime, strftime
if len(sys.argv) != 2:
    print 'Usage: %s [-t] [-p] ' % (sys.argv[0])
    sys.exit(1)
#Loads the log
if os.path.isfile("/home/user/.completed"):
	f = open( "/home/user/.completed" , "rwb" ) 
try:
	log = pickle.load( open( "/home/user/.completed" , "rb" ) )
except EOFError:
	log = []

#This adds an entry to log
def add_prompt():
 	log.append( {"id":(1 + len(log)), "time":time.gmtime(), "log":raw_input('Entry: ')} )
	
def add( entry ):
	log.append( {"id":(1 + len(log)), "time":time.gmtime(), "log":entry} )

#It is important that when removing items from the array that it is still kept in order
def remove():
	for x in log:
		print x["id"],strftime("%a, %d %b %Y %H:%M:%S", x["time"]), x["log"]
	index= input('Remove which Element: ') - 1
	del log[index]
	i=1;
	for x in log:
		x["id"] = i
		i = i + 1

if sys.argv[1] == "-a":
	add_prompt()
if sys.argv[1] == "-d":
	remove()


for x in log:
        print x["id"],strftime("%a, %d %b %Y %H:%M:%S", x["time"]), x["log"]

pickle.dump( log,  open( "/home/user/.completed", "wb" )  )
